version: '3.4'

networks:
  app-tier:
    driver: bridge

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        networks:
            - app-tier
        container_name: rabbitmq
           
        environment:
            #RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${guest}
            RABBITMQ_DEFAULT_PASS: ${guest}
        ports:
            - 5672:5672
            - 15672:15672

    privatbanktestapi:
        image: ${DOCKER_REGISTRY-}privatbanktestapi
        depends_on:
            - rabbitmq
        networks:
            - app-tier
        build:
            context: .
            dockerfile: PrivatBankTestApi/Dockerfile

    queryhandler:
        image: ${DOCKER_REGISTRY-}queryhandler
        environment:
            - rabbit_mq_host=rabbitmq
            - rabbit_mq_port=5672
            - rabbitmq_username=guest
            - rabbitmq_password=guest
        depends_on:
            - rabbitmq
        networks:
            - app-tier
        build:
            context: .
            dockerfile: QueryHandler/Dockerfile

  